### ISSUE TITLE
clientsCount updating strangely in stress test

### ISSUE THREAD

**Issue by aeosynth** [Automattic/engine.io#276]
i created a test which gets different results depending on the number of connections opened. is this a bug? tested on osx 10.9.4, node 0.10.30

connections opened: initial clientsCount -> count after timeout -> count after client is killed

100: 100 -> 0 (client exited cleanly)
150: 150 -> 0 -> 0
200: 200 ->116 -> 0
250: 242 -> 242 -> 119 -> 0 (after a minute)

the last test gave the error `(libuv) Failed to create kqueue (24)`, meaning i ran out of file descriptors

```js
var http = require('http')
var engine = require('engine.io')

var httpServer = http.createServer().listen(1337)
var eioServer = engine(httpServer)

;(function log() { 
  console.log(eioServer.clientsCount)
  setTimeout(log, 1000)
})()
```

```js
var COUNT = parseInt(process.argv[2])
var engine = require('engine.io-client')

var socks = []
while (COUNT--)
  socks.push(engine('ws://localhost:1337'))

setTimeout(function() {
  var sock
  while (sock = socks.pop())
    sock.close()
}, 1500)
```

**Comment by defunctzombie** [comment]
No issues using latest version that I was able to find. If you still see an issue, please explain how to reproduce.
