### ISSUE TITLE
Generic protocol tests

### ISSUE THREAD

**Issue by facboy** [Automattic/engine.io#278]
Hi,

I realise that the current tests are written for the Node implementation of engine.io, but it would be nice to have the 'black box' tests split out from the 'white box' ones, so that implementations for other languages/platforms could verify their compatibility with the Node implementation.  The black box tests would then become protocol tests.

It seems that most of the 'black box' like tests are in server.js and jsonp.js, but some of them are more 'white box' as they assume that the server is running in-process and they modify and access the internal server state.

**Comment by defunctzombie** [comment]
Issue and discussion belongs in [engine.io-protocol](https://github.com/Automattic/engine.io-protocol) where we could create and maintain generic server tests. I am happy to review PRs for this.

Until then, a good test is to spin up an engine.io server and have your implementation talk to it. I know that is not ideal as it makes the implementation the "protocol" but that is what we have for now.
