### ISSUE TITLE
After migrating from 0.9 to 1.2.0 socket.io which uses engine.io I have a problem

### ISSUE THREAD

**Issue by mudlee** [Automattic/engine.io#295]
I have to analyze and modify the events sent via socket.io but I see the protocol has been changed.
If I use 0.9, when I emit an event, I see that the http message contains the message I sent, starting with "5:::".
Example: 5:::MESSAGE!!!

If I use 1.2.0, I get a message like this: �42MESSAGE!

Question: is there a document somewhere about these type of changes? I really need to know that a http message I receive is a socket.io event, or not.

**Comment by defunctzombie** [comment]
Please see the [engine.io-protocol](https://github.com/Automattic/engine.io-protocol) repo for documentation
