### ISSUE TITLE
socket engine is dying when many clients are connected

### ISSUE THREAD

**Issue by flashmandv** [Automattic/engine.io#301]
I'm using latest 1.2.1 socket.io and my server dies constantly after more than 300 users are connected at the same time.
The server is not loaded, I turned the client and server debug and this is what got my attention:
SERVER:
Mon, 05 Jan 2015 17:36:39 GMT engine:socket sending packet "message" (0)
Mon, 05 Jan 2015 17:36:39 GMT engine:socket transport error
Mon, 05 Jan 2015 17:36:39 GMT engine:socket error triggered by discarded transport
Mon, 05 Jan 2015 17:36:39 GMT engine upgrading existing transport
Mon, 05 Jan 2015 17:36:39 GMT engine:socket might upgrade socket transport from "polling" to "websocket"
Mon, 05 Jan 2015 17:36:39 GMT engine intercepting request for path "/socket.io/"
Mon, 05 Jan 2015 17:36:39 GMT engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=1420479277863-33&sid=ycn4-IOFOlHkALe1AAJR"
Mon, 05 Jan 2015 17:36:39 GMT engine:ws received "2probe"
Mon, 05 Jan 2015 17:36:39 GMT engine:ws writing "3probe"
Mon, 05 Jan 2015 17:36:39 GMT engine intercepting request for path "/socket.io/"

CLIENT:
socket socket error {"type":"TransportError","description":0} +12ms
...
Failed to load resource: net::ERR_EMPTY_RESPONSE

SERVER CODE:
var io = require("socket.io")({'heartbeat interval':15, 'heartbeat timeout':40}); 
socket = io.listen(port);
socket.sockets.on("connection", onSocketConnection);

I really need help.
Thanks

**Comment by defunctzombie** [comment]
This issue does not have enough information to help us debug. It is possible your server has a memory issue or some other problem. Without a failing client/server we can run and load balance or a much more detailed reason for the failure we cannot debug this.

**Comment by flashmandv** [comment]
Here is all the possible debug info: https://github.com/Automattic/socket.io/issues/1925
