### ISSUE TITLE
upgrade ws package to fix windows installation fails

### ISSUE THREAD

**Issue by eikaramba** [Automattic/engine.io#308]
see https://github.com/BrowserSync/grunt-browser-sync/issues/95

the problem is the nan package used by WS. Hopefully i located it right that this package(engine.io) needs to adapt its dependencies.

**Comment by nkzawa** [comment]
Thanks for your report! WS is bumped to 0.7.1 on master.

https://github.com/Automattic/engine.io/commit/600ed08b69cb4e06084564a7db74b4a20faaf6da

**Comment by kovbal** [comment]
When do you plan to release a new version?
