### ISSUE TITLE
XHR long-polling stuck forever on "pending"

### ISSUE THREAD

**Issue by nolanlawson** [Automattic/engine.io#320]
Howdy, I'm trying to write an engine.io-based plugin on top of PouchDB, but I'm running into an error trying to get my tests to pass. I can repro the error in both Firefox (37) and Chrome (42). I'm using Mac OS X Yosemite and Node v0.10.36.

When my app falls back to long-polling, it eventually starts failing because the server never sends a response. The `'websocket'` transport works fine; it's just the `'polling'` transport that hangs:

![screenshot 2015-04-16 09 18 13](https://cloud.githubusercontent.com/assets/283842/7181546/999e5aac-e419-11e4-95ce-5d8ce41ab3e0.png)

I have a reproducible test case for this error. To repro, just run:

    git clone https://github.com/nolanlawson/socket-pouch.git --branch repro-bug
    cd socket-pouch
    npm install && npm run dev

(You will need ports 8080, 8000, and 2020 open.) Then open up this URL in a browser:

    http://127.0.0.1:8000/test/index.html?grep=test.basics.js-local

Notice that it works for awhile (creating and closing `Socket`s), but then eventually it just stops dead in its tracks. I can refresh the browser and it will start working again (briefly), so I'm guessing this is a client-side issue?

Let me know if I can provide any more info, or if there's a good way to debug this. I don't see any logs on either the server or the client side to give any hint of what's going on. The source code is here: https://github.com/nolanlawson/socket-pouch/tree/repro-bug

**Comment by nolanlawson** [comment]
OK, I can see that this is happening because there are 8 open pending GETs at the path:

    /engine.io/?EIO=3&transport=polling&t=1429386433980-9&sid=<sid>

What's weird is that I'm calling `close()` on all my clients, so shouldn't that cancel these requests? Is there some way to manually cancel them? Or do I need to just make sure I only have one socket per browser or something, instead of constantly closing and re-opening sockets?

**Comment by nolanlawson** [comment]
Never mind, I figured it out. My problem was I had too many open sockets that I wasn't `close()`ing.

Every open socket represents an open XHR GET longpoll request when you're in longpoll mode, and if you have >8 you're out of luck because the browser will stop sending any more requests. My bad.

**Comment by rauchg** [comment]
@nolanlawson have definitely stumbled upon this myself and it's puzzling, but I don't think there's much we can do…

**Comment by nolanlawson** [comment]
Yup, hopefully the next poor soul who runs into this problem will google it and find this issue. :smiley:.

**Comment by rauchg** [comment]
yep thanks @nolanlawson
